---
- hosts: webserver1
  become: yes

  vars:
    temploc: /tmp/ashnik
    filename: /nginx.conf

  tasks:
    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes

    - name: Installs Nginx web server
      yum: pkg=nginx state=installed update_cache=true

    - name: Remove directory content
      file:
        path: "{{ temploc }}"
        state: absent

    - name: Download Nginx conf file
      shell: 'git clone --depth 1 https://github.com/wprabhakar/ashnik.git {{ temploc }}'

    - name: copy the nginx.conf file
      copy:
        src: "{{ temploc }}/nginx.conf"
        dest: /etc/nginx/nginx.conf
        remote_src: yes

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: Ensure that NGINX is started at boot time
      service:
        name: nginx
        enabled: yes
        state: started

